import services_weather from "../assets/services_weather.svg"
import services_flight from "../assets/services_flight.svg"
import services_events from "../assets/services_events.svg"
import service_customization from "../assets/service_customization.svg"
import service_dot from "../assets/services_dot.svg"
import TopRome from "../assets/rome.jpg"
import TopLondon from "../assets/london.jpg"
import TopEurope from "../assets/europe.jpg"
import TopEuropeBg from "../assets/top_selling_bg.svg"
import TopAros from "../assets/top_aro.svg"
import Next1 from "../assets/next_1.svg"
import Next2 from "../assets/next_2.svg"
import Next3 from "../assets/next_3.svg"
import Nexttrip from "../assets/next_trip.svg"
import Company1 from "../assets/company-1.svg"
import Company2 from "../assets/company-2.svg"
import Company3 from "../assets/company-3.svg"
import Company4 from "../assets/company-4.svg"
import Company5 from "../assets/company-5.svg"
import InformationAro from "../assets/information_aro.svg"
import FooterIcon from "../assets/footer_icon.svg"

export {services_weather, services_flight, services_events, service_customization, service_dot , TopRome, TopLondon, TopEurope, TopEuropeBg , TopAros, Next1, Next2, Next3, Nexttrip, Company1, Company2, Company3, Company4, Company5, InformationAro, FooterIcon }